# SPDX-License-Identifier: MIT
---
- name: Ensure persistent log store exists
  file:
    path: "{{ __journald_persistent_path }}"
    state: directory
    owner: root
    group: systemd-journal
    mode: '2755'

- name: Apply tmpfiles.d snippet on persistent log store
  command:
    cmd: >
      systemd-tmpfiles --create
                       --prefix={{ __journald_persistent_path }}
                       {{ __journald_tmpfiles }}
  changed_when: false
